# Generated by Django 6.0.3 on 2026-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servidores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servidor",
            name="cursos",
        ),
        migrations.AddField(
            model_name="servidor",
            name="cursos",
            field=models.ManyToManyField(
                related_name="servidores", to="servidores.curso"
            ),
        ),
    ]
