# Generated by Django 6.0.3 on 2026-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servidores", "0002_remove_servidor_cursos_servidor_cursos"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="carga_horaria",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
