# Generated by Django 6.0.3 on 2026-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servidores", "0004_materia_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materia",
            name="cursos",
        ),
        migrations.AddField(
            model_name="curso",
            name="materias",
            field=models.ManyToManyField(
                related_name="cursos", to="servidores.materia"
            ),
        ),
    ]
